
# Copy this file to .streamlit/secrets.toml and fill in values.
[gdrive]
folder_id = "YOUR_FOLDER_ID"  # optional
# Paste your service account JSON inline as TOML object:
service_account = { 
  type = "service_account",
  project_id = "YOUR_PROJECT",
  private_key_id = "XXXX",
  private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  client_email = "xxx@xxx.iam.gserviceaccount.com",
  client_id = "1234567890",
  auth_uri = "https://accounts.google.com/o/oauth2/auth",
  token_uri = "https://oauth2.googleapis.com/token",
  auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs",
  client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/xxx%40xxx.iam.gserviceaccount.com"
}
